# Generated by Django 3.0 on 2022-11-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('idatt', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='IDATT')),
                ('iditem', models.CharField(default='', max_length=10)),
                ('attname', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idcrad', models.CharField(default='', max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], default='ชาย', max_length=6)),
                ('username', models.CharField(default='', max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('position', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('details', models.TextField(default='-', max_length=100, null=True)),
                ('idtype', models.CharField(default='', max_length=99)),
                ('serial', models.CharField(default='', max_length=11)),
                ('price', models.CharField(default='', max_length=10, null=True)),
                ('pricetype', models.CharField(default='', max_length=100, null=True)),
                ('date', models.CharField(default='', max_length=11, null=True)),
                ('acquisition', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('namelocation', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('idtype', models.CharField(default='', max_length=99, primary_key=True, serialize=False)),
                ('typecode', models.CharField(default='', max_length=99, null=True)),
                ('typedetails', models.CharField(default='', max_length=190, null=True)),
            ],
        ),
    ]
